### ISSUE TITLE
Layer frame not changing with Autolayout

### ISSUE THREAD

**Issue by zigdanis** [kentya6/KYCircularProgress#18] opened 2017-02-28 12:29 UTC
I'm using autolayout and I've set constraints to the KYCircularProgress view.
But after autolayout resized it's frame - KYCircularProgress's layer doesn't redraw according to the new frame.

**Comment by kentya6** [comment] 2017-06-03 13:01
Sorry for the late reply.
To resize your view in autolayout, you can use `NSLayoutConstraint`.
Connect `NSLayoutConstraint` outlet to `KYCircularProgress` width/height constraint, and resize your view via `NSLayoutConstraint` property.

**Comment by Steve-Munday** [comment] 2017-06-14 18:27
I have also experienced this problem in my project.  The problem is not resolved by adding constraints.  I have already setup constraints and my `KYCircularProgress` view is resizing correctly.  The problem is, as @zigdanis mentioned, the layer is not redrawing at the new size.  Here's a screenshot from IB Debug View Heirarchy, 

*Before resize*:
![screenshot 2017-06-14 14 25 04](https://user-images.githubusercontent.com/24897009/27148218-784ecbd0-510d-11e7-9422-cddb69410ff9.png)

*After resize*:
![screenshot 2017-06-14 14 24 31](https://user-images.githubusercontent.com/24897009/27148231-8902a938-510d-11e7-8ab5-4a36f4f2299b.png)

**Comment by kentya6** [comment] 2018-05-04 02:42
@zigdanis @Steve-Munday 
I updated this library to version 1.1.0 and fixed this problem.
Thanks. 👍

**Closed** 2018-10-08 12:05 UTC
